// Code generated by mockery v2.49.1. DO NOT EDIT.

package mocks

import (
	context "context"
	request "simple-dashboard-server/api/request"

	mock "github.com/stretchr/testify/mock"

	response "simple-dashboard-server/api/response"
)

// AuthService is an autogenerated mock type for the AuthService type
type AuthService struct {
	mock.Mock
}

// Login provides a mock function with given fields: ctx, req
func (_m *AuthService) Login(ctx context.Context, req request.LoginRequest) (response.LoginResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 response.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, request.LoginRequest) (response.LoginResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, request.LoginRequest) response.LoginResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(response.LoginResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, request.LoginRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NotifForgotPassword provides a mock function with given fields: ctx, req
func (_m *AuthService) NotifForgotPassword(ctx context.Context, req request.ResetPasswordRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for NotifForgotPassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, request.ResetPasswordRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Register provides a mock function with given fields: ctx, req
func (_m *AuthService) Register(ctx context.Context, req request.RegisterRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, request.RegisterRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ResetPassword provides a mock function with given fields: ctx, req
func (_m *AuthService) ResetPassword(ctx context.Context, req request.ResetPasswordConfirmRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ResetPassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, request.ResetPasswordConfirmRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VerifyEmail provides a mock function with given fields: ctx, req
func (_m *AuthService) VerifyEmail(ctx context.Context, req request.VerifyEmailRequest) (response.LoginResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for VerifyEmail")
	}

	var r0 response.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, request.VerifyEmailRequest) (response.LoginResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, request.VerifyEmailRequest) response.LoginResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(response.LoginResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, request.VerifyEmailRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuthService creates a new instance of AuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthService {
	mock := &AuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
