# fly.toml app configuration file generated for server-dark-star-8883 on 2024-11-30T19:26:39+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'server-dark-star-8883'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
