name: Setup Server and Client

on:
  pull_request:
    types:
      - closed
    branches:
      - main
  push:
    branches:
      - main

jobs:
  # testing in path /server using go
  server-test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go 1.23
        uses: actions/setup-go@v2
        with:
          go-version: 1.23
      - name: Install dependencies
        run: cd server && go mod tidy
      - name: Test
        run: cd server && go test ./... -v
      - name: Lint
        run: cd server && go fmt ./...

  # testing in path /client using nodejs yarn
  client-test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js 22.x
        uses: actions/setup-node@v2
        with:
          node-version: 22.x
      - name: Install dependencies
        run: cd client && yarn install
      - name: Test
        run: cd client && yarn test
      - name: Lint
        run: cd client && yarn lint
        
  
  